// <auto-generated />
namespace LegacyApplication.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IX_Internal_LightInfo_ControlNoAndLightNo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_Internal_LightInfo_ControlNoAndLightNo));
        
        string IMigrationMetadata.Id
        {
            get { return "201705230248313_IX_Internal_LightInfo_ControlNoAndLightNo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
