// <auto-generated />
namespace LegacyApplication.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateGroupLightInfo20170602 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateGroupLightInfo20170602));
        
        string IMigrationMetadata.Id
        {
            get { return "201706020126547_updateGroupLightInfo20170602"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
